In [1]:
import numpy as np

In [2]:
def conv_transpose_layer(X, kernel, stride=1, padding=0):
    # Girdi boyutlari
    X_h, X_w = X.shape

    # Kernel boyutlari
    k_h, k_w = kernel.shape

    # Cikis boyutlari
    out_h = (X_h - 1) * stride + k_h - 2 * padding
    out_w = (X_w - 1) * stride + k_w - 2 * padding

    # Cikti
    output = np.zeros((out_h, out_w))

    # Transpose Convolution islemi
    for i in range(X_h):
        for j in range(X_w):
            output[i * stride:i * stride + k_h, j * stride:j * stride + k_w] += X[i, j] * kernel

    return output

In [3]:
# Girdi (3x3)
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [4]:
# Filtre (2x2)
kernel = np.array([
    [1, 0],
    [0, -1]
])

In [5]:
output = conv_transpose_layer(X, kernel, stride=1, padding=0)
print(output)

[[ 1.  2.  3.  0.]
 [ 4.  4.  4. -3.]
 [ 7.  4.  4. -6.]
 [ 0. -7. -8. -9.]]
