In [1]:
import numpy as np

In [15]:
def pooling_layer(X, pool_size=2, stride=2, mode="max"):
    n_H, n_W, n_C = X.shape

    # Pooling cikti boyutlari
    out_height = (n_H - pool_size) // stride + 1
    out_width = (n_W - pool_size) // stride + 1

    # Cikis matrisi
    pooled_output = np.zeros((out_height, out_width, n_C))

    for h in range(out_height):
        for w in range(out_width):
            for c in range(n_C):
                # Pooling penceresi secilir
                h_start = h * stride
                h_end = h_start + pool_size
                w_start = w * stride
                w_end = w_start + pool_size

                X_slice = X[h_start:h_end, w_start:w_end, c]

                # Max Pooling
                if mode == "max":
                    pooled_output[h, w, c] = np.max(X_slice)
                # Average Pooling
                elif mode == "average":
                    pooled_output[h, w, c] = np.mean(X_slice)

    return pooled_output

In [20]:
# Girdi, 6x6 boyut, 1 kanal
X = np.array([
    [[41], [21], [15], [21], [69], [85]],
    [[44], [31], [90], [56], [24], [92]],
    [[28], [60], [81], [192], [184], [155]],
    [[29], [50], [93], [96], [99], [100]],
    [[161], [144], [169], [181], [240], [244]],
    [[3], [5], [7], [28], [290], [261]]
])

In [19]:
# Max Pooling, 2x2 boyut, stride 1
max_pool_stride_1 = pooling_layer(X, pool_size=2, stride=1, mode="max")
print(max_pool_stride_1)

[[[ 44.]
  [ 90.]
  [ 90.]
  [ 69.]
  [ 92.]]

 [[ 60.]
  [ 90.]
  [192.]
  [192.]
  [184.]]

 [[ 60.]
  [ 93.]
  [192.]
  [192.]
  [184.]]

 [[161.]
  [169.]
  [181.]
  [240.]
  [244.]]

 [[161.]
  [169.]
  [181.]
  [290.]
  [290.]]]


In [21]:
max_pool_stride_2 = pooling_layer(X, pool_size=2, stride=2, mode="max")
print(max_pool_stride_2)

[[[ 44.]
  [ 90.]
  [ 92.]]

 [[ 60.]
  [192.]
  [184.]]

 [[161.]
  [181.]
  [290.]]]
