In [1]:
import numpy as np

In [2]:
def zero_padding_layer(X, pad):
    pad_h, pad_w = pad
    X_padded = np.zeros((X.shape[0] + 2 * pad_h, X.shape[1] + 2 * pad_w))
    X_padded[pad_h:X.shape[0] + pad_h, pad_w:X.shape[1] + pad_w] = X
    return X_padded

In [3]:
# Girdi (3x3)
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [10]:
# Padding (her kenara 1 birim 0)
pad = (1, 1)

In [11]:
output = zero_padding_layer(X, pad)
print(output)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 0.]
 [0. 4. 5. 6. 0.]
 [0. 7. 8. 9. 0.]
 [0. 0. 0. 0. 0.]]
