In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
# Populasyon buyuklugu
POPULATION_SIZE = 100
# Mutasyon orani
MUTATION_RATE = 0.01
# Caprazlama orani
CROSSOVER_RATE = 0.8
# Maksimum jenerasyon sayisi
GENERATIONS = 50
# Gen uzunlugu (binary)
CHROMOSOME_LENGTH = 8

In [25]:
population = [np.random.randint(2, size=CHROMOSOME_LENGTH) for _ in range(POPULATION_SIZE)]

In [26]:
population[:5]

[array([1, 1, 0, 0, 1, 0, 1, 0]),
 array([1, 0, 1, 1, 1, 1, 0, 1]),
 array([0, 1, 0, 1, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1]),
 array([1, 1, 1, 0, 0, 0, 0, 0])]

In [27]:
def fitness_function(individual):
    x = int("".join(map(str, individual)), 2)
    return x ** 2

In [28]:
for generation in range(GENERATIONS):
    # Fitness skorlari hesaplanir
    fitness_scores = []
    for individual in population:
        score = fitness_score(individual)
        fitness_scores.append(score)

    # Yeni populasyon olusturulur
    new_population = []

    for _ in range(POPULATION_SIZE // 2):
        # Turnuva ile ebevenyler secilir
        participants = np.random.choice(len(population), size=3, replace=False)
        best = max(participants, key=lambda idx: fitness_scores[idx])
        parent1 = population[best]

        participants = np.random.choice(len(population), size=3, replace=False)
        best = max(participants, key=lambda idx: fitness_scores[idx])
        parent2 = population[best]

        # Caprazlama yapilir
        if np.random.rand() < CROSSOVER_RATE:
            point = np.random.randint(1, CHROMOSOME_LENGTH - 1)
            child1 = np.concatenate((parent1[:point], parent2[point:]))
            child2 = np.concatenate((parent2[:point], parent2[point:]))
        else:
            child1 = parent1
            child2 = parent2

        # Mutasyon
        for i in range(CHROMOSOME_LENGTH):
            if np.random.rand() < MUTATION_RATE:
                child1[i] = 1 - child1[i]  # 1 ise 0 yap, 0 ise 1 yap

        for i in range(CHROMOSOME_LENGTH):
            if np.random.rand() < MUTATION_RATE:
                child2[i] = 1 - child2[i]  # 1 ise 0 yap, 0 ise 1 yap

        
        # Yeni bireyler populasyona eklenir
        new_population.append(child1)
        new_population.append(child2)

    population = new_population

    # En iyi bireyi bul
    best_individual = max(population, key=lambda ind: fitness_function(ind))
    best_fitness = fitness_function(best_individual)
    print(f"Generation {generation + 1}: Best Fitness = {best_fitness}, Best Individual = {int(''.join(map(str, best_individual)), 2)}")

Generation 1: Best Fitness = 63001, Best Individual = 251
Generation 2: Best Fitness = 65025, Best Individual = 255
Generation 3: Best Fitness = 65025, Best Individual = 255
Generation 4: Best Fitness = 65025, Best Individual = 255
Generation 5: Best Fitness = 65025, Best Individual = 255
Generation 6: Best Fitness = 65025, Best Individual = 255
Generation 7: Best Fitness = 65025, Best Individual = 255
Generation 8: Best Fitness = 65025, Best Individual = 255
Generation 9: Best Fitness = 65025, Best Individual = 255
Generation 10: Best Fitness = 65025, Best Individual = 255
Generation 11: Best Fitness = 65025, Best Individual = 255
Generation 12: Best Fitness = 65025, Best Individual = 255
Generation 13: Best Fitness = 65025, Best Individual = 255
Generation 14: Best Fitness = 65025, Best Individual = 255
Generation 15: Best Fitness = 65025, Best Individual = 255
Generation 16: Best Fitness = 65025, Best Individual = 255
Generation 17: Best Fitness = 65025, Best Individual = 255
Genera